on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
        run: |
          echo "$SSH_PRIVATE_KEY" > azure_key
          chmod 600 azure_key
          mkdir -p ~/.ssh
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh -t -i azure_key devAkash@98.70.8.237 "sudo bash ~/deploy.sh"
